// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rdregu4mMb4hXErVfc3qjL
// Component: PG86SX5hUp
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { ProductCard } from "../../ProductCard"; // plasmic-import: Uz-bQox2j-/codeComponent
import Button from "../../Button"; // plasmic-import: V7BbCwr-pLu/component
import { MyTextInput } from "../../custom/MyTextInput"; // plasmic-import: 9reLl-KAYh/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: rdregu4mMb4hXErVfc3qjL/projectcss
import sty from "./PlasmicFeatures.module.css"; // plasmic-import: PG86SX5hUp/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: RCMerZM6K3F/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: vm-uGfGqmSN/icon

export type PlasmicFeatures__VariantMembers = {};

export type PlasmicFeatures__VariantsArgs = {};
type VariantPropType = keyof PlasmicFeatures__VariantsArgs;
export const PlasmicFeatures__VariantProps = new Array<VariantPropType>();

export type PlasmicFeatures__ArgsType = {};
type ArgPropType = keyof PlasmicFeatures__ArgsType;
export const PlasmicFeatures__ArgProps = new Array<ArgPropType>();

export type PlasmicFeatures__OverridesType = {
  root?: p.Flex<"div">;
  productCard?: p.Flex<typeof ProductCard>;
  featuresSubmit?: p.Flex<typeof Button>;
  custUsernameInput?: p.Flex<typeof MyTextInput>;
  custPasswordInput?: p.Flex<typeof MyTextInput>;
};

export interface DefaultFeaturesProps {}

function PlasmicFeatures__RenderFunc(props: {
  variants: PlasmicFeatures__VariantsArgs;
  args: PlasmicFeatures__ArgsType;
  overrides: PlasmicFeatures__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            sty.root
          )}
        >
          {true ? (
            <ProductCard
              data-plasmic-name={"productCard"}
              data-plasmic-override={overrides.productCard}
              className={classNames("__wab_instance", sty.productCard)}
            />
          ) : null}

          <Button
            data-plasmic-name={"featuresSubmit"}
            data-plasmic-override={overrides.featuresSubmit}
            className={classNames("__wab_instance", sty.featuresSubmit)}
          >
            {"Submit"}
          </Button>

          <MyTextInput
            data-plasmic-name={"custUsernameInput"}
            data-plasmic-override={overrides.custUsernameInput}
            className={classNames("__wab_instance", sty.custUsernameInput)}
            placeholder={"username" as const}
          />

          <MyTextInput
            data-plasmic-name={"custPasswordInput"}
            data-plasmic-override={overrides.custPasswordInput}
            className={classNames("__wab_instance", sty.custPasswordInput)}
            placeholder={"password" as const}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "productCard",
    "featuresSubmit",
    "custUsernameInput",
    "custPasswordInput"
  ],
  productCard: ["productCard"],
  featuresSubmit: ["featuresSubmit"],
  custUsernameInput: ["custUsernameInput"],
  custPasswordInput: ["custPasswordInput"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  productCard: typeof ProductCard;
  featuresSubmit: typeof Button;
  custUsernameInput: typeof MyTextInput;
  custPasswordInput: typeof MyTextInput;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFeatures__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFeatures__VariantsArgs;
    args?: PlasmicFeatures__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFeatures__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFeatures__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFeatures__ArgProps,
      internalVariantPropNames: PlasmicFeatures__VariantProps
    });

    return PlasmicFeatures__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFeatures";
  } else {
    func.displayName = `PlasmicFeatures.${nodeName}`;
  }
  return func;
}

export const PlasmicFeatures = Object.assign(
  // Top-level PlasmicFeatures renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    productCard: makeNodeComponent("productCard"),
    featuresSubmit: makeNodeComponent("featuresSubmit"),
    custUsernameInput: makeNodeComponent("custUsernameInput"),
    custPasswordInput: makeNodeComponent("custPasswordInput"),

    // Metadata about props expected for PlasmicFeatures
    internalVariantProps: PlasmicFeatures__VariantProps,
    internalArgProps: PlasmicFeatures__ArgProps
  }
);

export default PlasmicFeatures;
/* prettier-ignore-end */
