// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rdregu4mMb4hXErVfc3qjL
// Component: ZoPojSHpjk
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { MaterialTable } from "../../custom/MaterialTable"; // plasmic-import: Vtz-tLKOpa/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: rdregu4mMb4hXErVfc3qjL/projectcss
import sty from "./PlasmicTablePlace.module.css"; // plasmic-import: ZoPojSHpjk/css

export type PlasmicTablePlace__VariantMembers = {};

export type PlasmicTablePlace__VariantsArgs = {};
type VariantPropType = keyof PlasmicTablePlace__VariantsArgs;
export const PlasmicTablePlace__VariantProps = new Array<VariantPropType>();

export type PlasmicTablePlace__ArgsType = {};
type ArgPropType = keyof PlasmicTablePlace__ArgsType;
export const PlasmicTablePlace__ArgProps = new Array<ArgPropType>();

export type PlasmicTablePlace__OverridesType = {
  root?: p.Flex<"div">;
  tablePLaceTable1?: p.Flex<typeof MaterialTable>;
};

export interface DefaultTablePlaceProps {}

function PlasmicTablePlace__RenderFunc(props: {
  variants: PlasmicTablePlace__VariantsArgs;
  args: PlasmicTablePlace__ArgsType;
  overrides: PlasmicTablePlace__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            sty.root
          )}
        >
          <MaterialTable
            data-plasmic-name={"tablePLaceTable1"}
            data-plasmic-override={overrides.tablePLaceTable1}
            className={classNames("__wab_instance", sty.tablePLaceTable1)}
            headerOption={[
              { id: "id", numeric: true, disablePadding: false, label: "Id" },
              {
                id: "client_name",
                numeric: false,
                disablePadding: true,
                label: "Client Name"
              },
              {
                id: "bid_code",
                numeric: false,
                disablePadding: false,
                label: "Bid Code"
              },
              {
                id: "bid_amount",
                numeric: true,
                disablePadding: false,
                label: "Bid Amount"
              },
              {
                id: "bid_date",
                numeric: false,
                disablePadding: false,
                label: "Bid Time"
              },
              {
                id: "status",
                numeric: false,
                disablePadding: false,
                label: "Status"
              }
            ]}
            orderBy={"bidAmount" as const}
            orderType={"desc" as const}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "tablePLaceTable1"],
  tablePLaceTable1: ["tablePLaceTable1"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  tablePLaceTable1: typeof MaterialTable;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTablePlace__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTablePlace__VariantsArgs;
    args?: PlasmicTablePlace__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTablePlace__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTablePlace__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTablePlace__ArgProps,
      internalVariantPropNames: PlasmicTablePlace__VariantProps
    });

    return PlasmicTablePlace__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTablePlace";
  } else {
    func.displayName = `PlasmicTablePlace.${nodeName}`;
  }
  return func;
}

export const PlasmicTablePlace = Object.assign(
  // Top-level PlasmicTablePlace renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    tablePLaceTable1: makeNodeComponent("tablePLaceTable1"),

    // Metadata about props expected for PlasmicTablePlace
    internalVariantProps: PlasmicTablePlace__VariantProps,
    internalArgProps: PlasmicTablePlace__ArgProps
  }
);

export default PlasmicTablePlace;
/* prettier-ignore-end */
