// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rdregu4mMb4hXErVfc3qjL
// Component: By3pjKN_kh
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { ReactBootstrapNavBar } from "../../custom/ReactBootstrapNavBar"; // plasmic-import: 5ilRP34x6Y/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: rdregu4mMb4hXErVfc3qjL/projectcss
import sty from "./PlasmicNavBarMenu.module.css"; // plasmic-import: By3pjKN_kh/css

export type PlasmicNavBarMenu__VariantMembers = {};

export type PlasmicNavBarMenu__VariantsArgs = {};
type VariantPropType = keyof PlasmicNavBarMenu__VariantsArgs;
export const PlasmicNavBarMenu__VariantProps = new Array<VariantPropType>();

export type PlasmicNavBarMenu__ArgsType = {};
type ArgPropType = keyof PlasmicNavBarMenu__ArgsType;
export const PlasmicNavBarMenu__ArgProps = new Array<ArgPropType>();

export type PlasmicNavBarMenu__OverridesType = {
  root?: p.Flex<"div">;
  navBarMenuMainMenu?: p.Flex<typeof ReactBootstrapNavBar>;
};

export interface DefaultNavBarMenuProps {}

function PlasmicNavBarMenu__RenderFunc(props: {
  variants: PlasmicNavBarMenu__VariantsArgs;
  args: PlasmicNavBarMenu__ArgsType;
  overrides: PlasmicNavBarMenu__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            sty.root
          )}
        >
          <ReactBootstrapNavBar
            data-plasmic-name={"navBarMenuMainMenu"}
            data-plasmic-override={overrides.navBarMenuMainMenu}
            className={classNames("__wab_instance", sty.navBarMenuMainMenu)}
            items={[
              {
                title: "Link1",
                action: "#link1",
                type: "single",
                children: []
              },
              { title: "", action: "", type: "divider", children: [] },
              {
                title: "Nested1",
                action: "",
                type: "nested",
                children: [
                  {
                    title: "inner1",
                    action: "innerLink1",
                    type: "single",
                    children: []
                  }
                ]
              }
            ]}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navBarMenuMainMenu"],
  navBarMenuMainMenu: ["navBarMenuMainMenu"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBarMenuMainMenu: typeof ReactBootstrapNavBar;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavBarMenu__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavBarMenu__VariantsArgs;
    args?: PlasmicNavBarMenu__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNavBarMenu__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicNavBarMenu__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNavBarMenu__ArgProps,
      internalVariantPropNames: PlasmicNavBarMenu__VariantProps
    });

    return PlasmicNavBarMenu__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavBarMenu";
  } else {
    func.displayName = `PlasmicNavBarMenu.${nodeName}`;
  }
  return func;
}

export const PlasmicNavBarMenu = Object.assign(
  // Top-level PlasmicNavBarMenu renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBarMenuMainMenu: makeNodeComponent("navBarMenuMainMenu"),

    // Metadata about props expected for PlasmicNavBarMenu
    internalVariantProps: PlasmicNavBarMenu__VariantProps,
    internalArgProps: PlasmicNavBarMenu__ArgProps
  }
);

export default PlasmicNavBarMenu;
/* prettier-ignore-end */
