// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rdregu4mMb4hXErVfc3qjL
// Component: ymPlshSjp4
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { MaterialMultiSelect } from "../../custom/MaterialMultiSelect"; // plasmic-import: 7CJnSohl3d/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: rdregu4mMb4hXErVfc3qjL/projectcss
import sty from "./PlasmicFormPost.module.css"; // plasmic-import: ymPlshSjp4/css

export type PlasmicFormPost__VariantMembers = {};

export type PlasmicFormPost__VariantsArgs = {};
type VariantPropType = keyof PlasmicFormPost__VariantsArgs;
export const PlasmicFormPost__VariantProps = new Array<VariantPropType>();

export type PlasmicFormPost__ArgsType = {};
type ArgPropType = keyof PlasmicFormPost__ArgsType;
export const PlasmicFormPost__ArgProps = new Array<ArgPropType>();

export type PlasmicFormPost__OverridesType = {
  root?: p.Flex<"div">;
  formPostTagSelect1?: p.Flex<typeof MaterialMultiSelect>;
};

export interface DefaultFormPostProps {}

function PlasmicFormPost__RenderFunc(props: {
  variants: PlasmicFormPost__VariantsArgs;
  args: PlasmicFormPost__ArgsType;
  overrides: PlasmicFormPost__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            sty.root
          )}
        >
          <MaterialMultiSelect
            data-plasmic-name={"formPostTagSelect1"}
            data-plasmic-override={overrides.formPostTagSelect1}
            className={classNames("__wab_instance", sty.formPostTagSelect1)}
            label={"tag" as const}
            options={[
              { id: "opt1", value: "Opt1" },
              { id: "opt2", value: "Opt2" },
              { id: "opt3", value: "Opt3" },
              { id: "opt4", value: "Opt4" }
            ]}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "formPostTagSelect1"],
  formPostTagSelect1: ["formPostTagSelect1"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  formPostTagSelect1: typeof MaterialMultiSelect;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFormPost__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFormPost__VariantsArgs;
    args?: PlasmicFormPost__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFormPost__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFormPost__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFormPost__ArgProps,
      internalVariantPropNames: PlasmicFormPost__VariantProps
    });

    return PlasmicFormPost__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFormPost";
  } else {
    func.displayName = `PlasmicFormPost.${nodeName}`;
  }
  return func;
}

export const PlasmicFormPost = Object.assign(
  // Top-level PlasmicFormPost renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    formPostTagSelect1: makeNodeComponent("formPostTagSelect1"),

    // Metadata about props expected for PlasmicFormPost
    internalVariantProps: PlasmicFormPost__VariantProps,
    internalArgProps: PlasmicFormPost__ArgProps
  }
);

export default PlasmicFormPost;
/* prettier-ignore-end */
